################################################################################
# IPTFT product  
#
# Author: Andrei Mironenko <andrei.mironenko@paralleldynamic.com>
################################################################################

# Development build is based on release one with some packages which are taken 
# from the cutting edge of the Git sources
require ../rel/libs.inc

################################################################################
# Additional packages for the development build 
################################################################################
TASK_APPS_LIBS += "\
 "
 
################################################################################
# Git cutting edge version of libraries                                        #
################################################################################

